# Documentation
# This file defines safety rules that the MXCP Project Assistant must follow.
# These rules are automatically enforced when working with MXCP projects.
# They complement the core MXCP specification by adding project-specific safety measures.
#
# Integration with MXCP Project Assistant:
# 1. Pre-change validation: Assistant must check git status and tests before changes
# 2. Protected paths: Assistant cannot modify protected directories without explicit permission
# 3. Change validation: All changes must pass tests and validation before being committed
# 4. Documentation: Changes must include proper documentation of impact and test coverage
#
# See the MXCP Project Assistant documentation for the complete specification of
# endpoint creation, validation, and testing requirements.

version: "1.0"

# ===================
# DBT Layer Controls
# ===================
dbt:
  protected:
    directories:
      - models/
      - seeds/
      - tests/
      - macros/
    files:
      - dbt_project.yml

  pre_change_requirements:
    - git_status_clean
    - dbt_compile_success
    - dbt_test_success

  modification_protocols:
    models:
      - must_preserve_column_order
      - must_preserve_existing_tests
    seeds:
      - must_preserve_header_row
      - must_maintain_delimiter

  post_change_validation:
    - dbt_compile
    - dbt_test
    - git_diff_review

# ===================
# MXCP Layer Controls
# ===================
mxcp:
  protected:
    directories:
      - tools/
      - resources/
      - prompts/
    files:
      - mxcp-site.yml

  pre_change_requirements:
    - git_status_clean
    - mxcp_validate_success
    - endpoint_tests_success

  modification_protocols:
    endpoints:
      - must_preserve_schema_version
      - must_validate_yaml_syntax
      - must_include_description
      - must_define_return_type
    implementations:
      - must_match_parameter_count
      - must_include_tests

  post_change_validation:
    - mxcp_validate
    - endpoint_tests
    - git_diff_review

# ===================
# Common Controls
# ===================
common:
  git:
    pre_change:
      - status_clean
      - on_correct_branch
    post_change:
      - review_diff
      - run_all_tests
      - commit_with_description

  error_handling:
    on_validation_failure:
      - git_checkout_previous
      - notify_user

  documentation:
    dbt_changes:
      must_include:
        - change_reason
        - data_impact
        - test_coverage
    mxcp_changes:
      must_include:
        - change_reason
        - api_impact
        - test_coverage 