version: 2
models:
  - name: dim_licenses
    version: 1
    description: "Dimension table for UAE business licenses, containing one record per license."
    latest_version: 1

    config:
      owner: "RAW"
      tags: ["marts"]

    versions:
      - v: 1

    columns:
      - name: license_pk
        data_type: varchar
        description: "The unique primary key for each license, generated as a hash of authority and license number."
        tests:
          - not_null

      - name: bl
        description: "The official business license number (BL #)."
        data_type: varchar
        tests:
          - not_null

      - name: bl_cbls
        description: "The BL CBLS number."
        data_type: varchar
        tests:
          - not_null

      - name: emirate_name_en
        description: "The English name of the Emirate where the license is registered."
        data_type: varchar
        tests:
          - not_null
          - accepted_values:
              values: ['Dubai', 'Abu Dhabi', 'Sharjah', 'Ajman', 'Ras Al Khaimah', 'Fujairah', 'Umm Al Quwain', 'Umm Al-Quwain']

      - name: emirate_name_ar
        description: "The Arabic name of the Emirate where the license is registered."
        data_type: varchar
        tests:
          - not_null

      - name: issuance_authority_en
        description: "The English name of the license issuing authority."
        data_type: varchar
        tests:
          - not_null

      - name: issuance_authority_ar
        description: "The Arabic name of the license issuing authority."
        data_type: varchar
        tests:
          - not_null

      - name: issuance_authority_branch_en
        description: "The English name of the issuing authority's branch."
        data_type: varchar

      - name: issuance_authority_branch_ar
        description: "The Arabic name of the issuing authority's branch."
        data_type: varchar

      - name: bl_status_en
        description: "The current status of the business license (e.g., Active, Expired)."
        data_type: varchar
        tests:
          - not_null
          - accepted_values:
              values: [
                  'Active', 'Expired', 'Cancelled', 'Current', 'On Hold', 'In  Active', 'Inactive',
                  'Blocked', 'Suspended', 'Under Liquidation', 'Under Commercial Liquidation',
                  'Under Commercial Liquidation.', 'Under Commercial Liquida', 'Under Commercial Mortgage'
                ]

      - name: bl_status_ar
        description: "The current status of the business license in Arabic."
        data_type: varchar
        tests:
          - not_null

      - name: bl_name_en
        description: "The English name of the business on the license."
        data_type: varchar

      - name: bl_name_ar
        description: "The Arabic name of the business on the license."
        data_type: varchar

      - name: bl_legal_type_en
        description: "The legal type of the business entity."
        data_type: varchar
        tests:
          - not_null

      - name: bl_legal_type_ar
        description: "The legal type of the business entity in Arabic."
        data_type: varchar
        tests:
          - not_null

      - name: bl_est_date
        description: "The establishment date of the license as a raw string."
        data_type: varchar
        tests:
          - not_null

      - name: bl_exp_date
        description: "The expiration date of the license as a raw string."
        data_type: varchar
        tests:
          - not_null

      - name: bl_type_en
        data_type: varchar
        description: "The type of business license in English (e.g., Commercial, Professional)."
        tests:
          - not_null
          - assert_bl_type_en_accepted_values

      - name: bl_type_ar
        description: "The type of business license in Arabic."
        data_type: varchar
        tests:
          - not_null

      - name: license_branch_flag
        description: "A flag indicating if the license is for a branch ('Y' or 'N')."
        tests:
          - accepted_values:
              values: ['Y', 'N']
        data_type: varchar

      - name: bl_full_address
        description: "The full address of the business."
        data_type: varchar
        tests:
          - not_null:
              where: "bl_full_address IS NOT NULL"

      - name: parent_licence_license_number
        description: "The license number of the parent license."
        data_type: varchar
        tests:
          - not_null:
              where: "parent_licence_license_number IS NOT NULL"

      - name: parent_license_issuance_authority_en
        data_type: varchar
        description: "The English name of the parent license's issuing authority."
        tests:
          - accepted_values:
              values: [
                'ADGM',
                'Abu Dhabi Department of Economic Development',
                'DMCC',
                'Department of Economic Development',
                'Dubai Silicon Oasis Authority',
                'Dubai South',
                'KEZAD',
                'Municipality',
                'Sharjah Economic Development Department',
                'Sharjah Publishing City',
                'Abu Dhabi Airports Free Zone',
                'Umm Al Quwain Department of Economic Development',
                'Ras Al Khaimah Economic Zone (RAKEZ)',
                'Dibba Municipality',
                'Dubai Airport Free Zone Authority',
                'Ras Al Khaimah Tourism Development Authority',
                'Sharjah Airport International Free Zone Authority',
                'Dubai Department of Economy & Tourism',
                'Fujairah Municipality',
                'Ajman Department of Economic Development',
                'Ras Al Khaimah Department of Economic Development'
              ]

      - name: parent_license_issuance_authority_ar
        data_type: varchar
        description: "The Arabic name of the parent license's issuing authority."
        tests:
          - accepted_values:
              values: [
                'بلدية',
                'دائرة التنمية الاقتصادية',
                'دائرة التنمية الاقتصادية في أبوظبي',
                'دائرة التنمية الاقتصادية في الشارقة',
                'دبي الجنوب',
                'سلطة واحة دبي للسيليكون',
                'سوق أبوظبي العالمي',
                'مجموعة كيزاد',
                'مركز دبي للسلع المتعددة',
                'هيئة مناطق رأس الخيمة الاقتصادية-راكز',
                'المنطقة الحرة بمطار دبي - DAFZA',
                'دائرة التنمية الاقتصادية في أم القيوين',
                'دائرة التنمية الاقتصادية في عجمان',
                'المنطقة الحرة لمطارات أبو ظبي - ADAFZ',
                'دائرة التنمية الإقتصادية في الشارقة',
                'بلدية دبا الفجيرة',
                'المنطقة الحرة لمطار الشارقة الدولي',
                'دائرة التنمية الاقتصادية في راس الخيمة',
                'دائرة الأقتصاد والسياحة دبى',
                'دائرة التنمية الاقتصادية في أبو ظبي',
                'بلدية الفجيرة',
                'هيئة رأس الخيمة لتنمية السياحة'
              ]

      - name: relationship_type_en
        description: "The relationship type of the owner to the license (e.g., Owner, Partner)."
        data_type: varchar
        tests:
          - not_null

      - name: relationship_type_ar
        description: "The relationship type of the owner to the license in Arabic."
        data_type: varchar
        tests:
          - not_null

      - name: owner_nationality_ar
        data_type: varchar
        description: "The nationality of the owner in Arabic."
        tests:
          - not_null

      - name: owner_gender
        data_type: varchar
        description: "The gender of the owner."
        tests:
          - not_null
          - accepted_values:
              values: ['Male', 'Female', 'UnKnown']

      - name: owner_nationality_en
        description: "The nationality of the owner in English."
        data_type: varchar
        tests:
          - not_null

      - name: business_activity_code
        description: "The code for the business activity."
        data_type: varchar
        tests:
          - not_null:
              where: "business_activity_code IS NOT NULL"

      - name: business_activity_desc_en
        description: "The English description of the business activity."
        data_type: varchar
        tests:
          - not_null:
              where: "business_activity_desc_en IS NOT NULL"

      - name: business_activity_desc_ar
        description: "The Arabic description of the business activity."
        data_type: varchar
        tests:
          - not_null:
              where: "business_activity_desc_ar IS NOT NULL"

      - name: license_latitude
        description: "The latitude of the business in DMS format."
        data_type: varchar
        tests:
          - not_null:
              where: "license_latitude IS NOT NULL"

      - name: license_longitude
        description: "The longitude of the business in DMS format."
        data_type: varchar
        tests:
          - not_null:
              where: "license_longitude IS NOT NULL"

      - name: license_latitude_1
        description: "An alternative latitude of the business in DMS format."
        data_type: varchar
        tests:
          - not_null:
              where: "license_latitude_1 IS NOT NULL"

      - name: license_longitude_1
        description: "An alternative longitude of the business in DMS format."
        data_type: varchar
        tests:
          - not_null:
              where: "license_longitude_1 IS NOT NULL"

      - name: bl_est_date_d
        description: "The establishment date of the license as a proper date."
        data_type: date
        tests:
          - not_null

      - name: bl_exp_date_d
        description: "The expiration date of the license as a proper date."
        data_type: date
        tests:
          - not_null

      - name: lat_dd
        description: "The latitude of the business in decimal degrees."
        data_type: double
        tests:
          - not_null:
              where: "lat_dd IS NOT NULL"

      - name: lon_dd
        description: "The longitude of the business in decimal degrees."
        data_type: double
        tests:
          - not_null:
              where: "lon_dd IS NOT NULL"
