version: 2
models:
  - name: dim_licenses
    description: "Dimension table for UAE business licenses, containing one record per license."
    columns:
      - name: license_pk
        description: "The unique primary key for each license, generated as a hash of authority and license number."
        tests:
          - not_null

      - name: bl
        description: "The official business license number (BL #)."
        tests:
          - not_null

      - name: emirate_name_en
        description: "The English name of the Emirate where the license is registered."
        tests:
          - not_null
          - accepted_values:
              values: ['Dubai', 'Abu Dhabi', 'Sharjah', 'Ajman', 'Ras Al Khaimah', 'Fujairah', 'Umm Al Quwain', 'Umm Al-Quwain']

      - name: issuance_authority_en
        description: "The English name of the license issuing authority."
        tests:
          - not_null

      - name: bl_status_en
        description: "The current status of the business license (e.g., Active, Expired)."
        tests:
          - not_null
          - accepted_values:
              values: [
                  'Active', 'Expired', 'Cancelled', 'Current', 'On Hold', 'In  Active', 'Inactive',
                  'Blocked', 'Suspended', 'Under Liquidation', 'Under Commercial Liquidation',
                  'Under Commercial Liquidation.', 'Under Commercial Liquida', 'Under Commercial Mortgage'
                ]

      - name: bl_legal_type_en
        description: "The legal type of the business entity."
        tests:
          - not_null

      - name: bl_est_date
        description: "The establishment date of the license."
        tests:
          - not_null

      - name: bl_exp_date
        description: "The expiration date of the license."
        tests:
          - not_null

      - name: bl_legal_type_ar
        description: "The legal type of the business license in Arabic."
        tests:
          - not_null

      - name: bl_type_en
        description: "The type of business license in English (e.g., Commercial, Professional)."
        tests:
          - not_null
          - assert_bl_type_en_accepted_values

      - name: bl_type_ar
        description: "The type of business license in Arabic."
        tests:
          - not_null

      - name: license_branch_flag
        description: "A flag indicating if the license is for a branch ('Y' or 'N'). Can be NULL."
        tests:
          - accepted_values:
              values: ['Y', 'N']

      - name: parent_licence_license_number
        description: "The license number of the parent license."

      - name: parent_license_issuance_authority_en
        description: "The English name of the parent license's issuing authority."

      - name: parent_license_issuance_authority_ar
        description: "The Arabic name of the parent license's issuing authority."

      - name: relationship_type_en
        description: "The relationship type of the owner to the license (e.g., Owner, Partner)."
        tests:
          - not_null

      - name: owner_nationality_ar
        description: "The nationality of the owner in Arabic."
        tests:
          - not_null

      - name: owner_gender
        description: "The gender of the owner."
        tests:
          - not_null
          - accepted_values:
              values: ['Male', 'Female', 'UnKnown']

      - name: owner_nationality_en
        description: "The nationality of the owner in English."
        tests:
          - not_null

      - name: business_activity_code
        description: "The code for the business activity."
        tests:
          - not_null
