version: 2
models:
  - name: dim_licenses
    description: "Dimension table for UAE business licenses, containing one record per license."
    columns:
      - name: license_pk
        description: "The unique primary key for each license, generated as a hash of authority and license number."
        tests:
          - unique
          - not_null

      - name: bl
        description: "The official business license number (BL #)."
        tests:
          - not_null

      - name: emirate_name_en
        description: "The English name of the Emirate where the license is registered."
        tests:
          - not_null
          - accepted_values:
              values: ['Dubai', 'Abu Dhabi', 'Sharjah', 'Ajman', 'Ras Al Khaimah', 'Fujairah', 'Umm Al Quwain', 'Umm Al-Quwain']

      - name: issuance_authority_en
        description: "The English name of the license issuing authority."
        tests:
          - not_null

      - name: bl_status_en
        description: "The current status of the business license (e.g., Active, Expired)."
        tests:
          - not_null
          - accepted_values:
              values: [
                  'Active', 'Expired', 'Cancelled', 'Current', 'On Hold', 'In  Active', 'Inactive',
                  'Blocked', 'Suspended', 'Under Liquidation', 'Under Commercial Liquidation'
                ]

      - name: bl_legal_type_en
        description: "The legal type of the business entity."
        tests:
          - not_null

      - name: bl_est_date
        description: "The establishment date of the license."
        tests:
          - not_null

      - name: bl_exp_date
        description: "The expiration date of the license."
        tests:
          - not_null
