SELECT DISTINCT
  CASE 
    WHEN $field = 'license_pk' THEN CAST(license_pk AS VARCHAR)
    WHEN $field = 'bl' THEN CAST(bl AS VARCHAR)
    WHEN $field = 'bl_cbls' THEN CAST(bl_cbls AS VARCHAR)
    WHEN $field = 'emirate_name_en' THEN CAST(emirate_name_en AS VARCHAR)
    WHEN $field = 'emirate_name_ar' THEN CAST(emirate_name_ar AS VARCHAR)
    WHEN $field = 'issuance_authority_en' THEN CAST(issuance_authority_en AS VARCHAR)
    WHEN $field = 'issuance_authority_ar' THEN CAST(issuance_authority_ar AS VARCHAR)
    WHEN $field = 'issuance_authority_branch_en' THEN CAST(issuance_authority_branch_en AS VARCHAR)
    WHEN $field = 'issuance_authority_branch_ar' THEN CAST(issuance_authority_branch_ar AS VARCHAR)
    WHEN $field = 'bl_status_en' THEN CAST(bl_status_en AS VARCHAR)
    WHEN $field = 'bl_status_ar' THEN CAST(bl_status_ar AS VARCHAR)
    WHEN $field = 'bl_name_en' THEN CAST(bl_name_en AS VARCHAR)
    WHEN $field = 'bl_name_ar' THEN CAST(bl_name_ar AS VARCHAR)
    WHEN $field = 'bl_legal_type_en' THEN CAST(bl_legal_type_en AS VARCHAR)
    WHEN $field = 'bl_legal_type_ar' THEN CAST(bl_legal_type_ar AS VARCHAR)
    WHEN $field = 'bl_type_en' THEN CAST(bl_type_en AS VARCHAR)
    WHEN $field = 'bl_type_ar' THEN CAST(bl_type_ar AS VARCHAR)
    WHEN $field = 'license_branch_flag' THEN CAST(license_branch_flag AS VARCHAR)
    WHEN $field = 'parent_license_issuance_authority_en' THEN CAST(parent_license_issuance_authority_en AS VARCHAR)
    WHEN $field = 'parent_license_issuance_authority_ar' THEN CAST(parent_license_issuance_authority_ar AS VARCHAR)
    WHEN $field = 'relationship_type_en' THEN CAST(relationship_type_en AS VARCHAR)
    WHEN $field = 'relationship_type_ar' THEN CAST(relationship_type_ar AS VARCHAR)
    WHEN $field = 'owner_nationality_ar' THEN CAST(owner_nationality_ar AS VARCHAR)
    WHEN $field = 'owner_gender' THEN CAST(owner_gender AS VARCHAR)
    WHEN $field = 'owner_nationality_en' THEN CAST(owner_nationality_en AS VARCHAR)
    WHEN $field = 'business_activity_desc_en' THEN CAST(business_activity_desc_en AS VARCHAR)
    WHEN $field = 'business_activity_desc_ar' THEN CAST(business_activity_desc_ar AS VARCHAR)
    WHEN $field = 'license_latitude' THEN CAST(license_latitude AS VARCHAR)
    WHEN $field = 'license_longitude' THEN CAST(license_longitude AS VARCHAR)
    WHEN $field = 'license_latitude_1' THEN CAST(license_latitude_1 AS VARCHAR)
    WHEN $field = 'license_longitude_1' THEN CAST(license_longitude_1 AS VARCHAR)
  END as value,
  CASE 
    WHEN $includeCount THEN COUNT(*)
    ELSE NULL
  END as count
FROM dim_licenses_v1
WHERE CASE 
    WHEN $field = 'license_pk' THEN CAST(license_pk AS VARCHAR)
    WHEN $field = 'bl' THEN CAST(bl AS VARCHAR)
    WHEN $field = 'bl_cbls' THEN CAST(bl_cbls AS VARCHAR)
    WHEN $field = 'emirate_name_en' THEN CAST(emirate_name_en AS VARCHAR)
    WHEN $field = 'emirate_name_ar' THEN CAST(emirate_name_ar AS VARCHAR)
    WHEN $field = 'issuance_authority_en' THEN CAST(issuance_authority_en AS VARCHAR)
    WHEN $field = 'issuance_authority_ar' THEN CAST(issuance_authority_ar AS VARCHAR)
    WHEN $field = 'issuance_authority_branch_en' THEN CAST(issuance_authority_branch_en AS VARCHAR)
    WHEN $field = 'issuance_authority_branch_ar' THEN CAST(issuance_authority_branch_ar AS VARCHAR)
    WHEN $field = 'bl_status_en' THEN CAST(bl_status_en AS VARCHAR)
    WHEN $field = 'bl_status_ar' THEN CAST(bl_status_ar AS VARCHAR)
    WHEN $field = 'bl_name_en' THEN CAST(bl_name_en AS VARCHAR)
    WHEN $field = 'bl_name_ar' THEN CAST(bl_name_ar AS VARCHAR)
    WHEN $field = 'bl_legal_type_en' THEN CAST(bl_legal_type_en AS VARCHAR)
    WHEN $field = 'bl_legal_type_ar' THEN CAST(bl_legal_type_ar AS VARCHAR)
    WHEN $field = 'bl_type_en' THEN CAST(bl_type_en AS VARCHAR)
    WHEN $field = 'bl_type_ar' THEN CAST(bl_type_ar AS VARCHAR)
    WHEN $field = 'license_branch_flag' THEN CAST(license_branch_flag AS VARCHAR)
    WHEN $field = 'parent_license_issuance_authority_en' THEN CAST(parent_license_issuance_authority_en AS VARCHAR)
    WHEN $field = 'parent_license_issuance_authority_ar' THEN CAST(parent_license_issuance_authority_ar AS VARCHAR)
    WHEN $field = 'relationship_type_en' THEN CAST(relationship_type_en AS VARCHAR)
    WHEN $field = 'relationship_type_ar' THEN CAST(relationship_type_ar AS VARCHAR)
    WHEN $field = 'owner_nationality_ar' THEN CAST(owner_nationality_ar AS VARCHAR)
    WHEN $field = 'owner_gender' THEN CAST(owner_gender AS VARCHAR)
    WHEN $field = 'owner_nationality_en' THEN CAST(owner_nationality_en AS VARCHAR)
    WHEN $field = 'business_activity_desc_en' THEN CAST(business_activity_desc_en AS VARCHAR)
    WHEN $field = 'business_activity_desc_ar' THEN CAST(business_activity_desc_ar AS VARCHAR)
    WHEN $field = 'license_latitude' THEN CAST(license_latitude AS VARCHAR)
    WHEN $field = 'license_longitude' THEN CAST(license_longitude AS VARCHAR)
    WHEN $field = 'license_latitude_1' THEN CAST(license_latitude_1 AS VARCHAR)
    WHEN $field = 'license_longitude_1' THEN CAST(license_longitude_1 AS VARCHAR)
  END IS NOT NULL
GROUP BY value
ORDER BY count DESC NULLS LAST, value