SELECT *
FROM dim_licenses_v1
WHERE 1=1
  AND ($LicensePk IS NULL OR license_pk = $LicensePk)
  AND ($Bl IS NULL OR bl = $Bl)
  AND ($Cbls IS NULL OR bl_cbls = $Cbls)
  AND ($EmirateNameEn IS NULL OR emirate_name_en ILIKE '%' || $EmirateNameEn || '%')
  AND ($EmirateNameAr IS NULL OR emirate_name_ar ILIKE '%' || $EmirateNameAr || '%')
  AND ($IssuanceAuthorityEn IS NULL OR issuance_authority_en = $IssuanceAuthorityEn)
  AND ($IssuanceAuthorityAr IS NULL OR issuance_authority_ar = $IssuanceAuthorityAr)
  AND ($IssuanceAuthorityBranchEn IS NULL OR issuance_authority_branch_en = $IssuanceAuthorityBranchEn)
  AND ($IssuanceAuthorityBranchAr IS NULL OR issuance_authority_branch_ar = $IssuanceAuthorityBranchAr)
  AND ($StatusEn IS NULL OR bl_status_en = $StatusEn)
  AND ($StatusAr IS NULL OR bl_status_ar = $StatusAr)
  AND ($NameEn IS NULL OR bl_name_en ILIKE '%' || $NameEn || '%')
  AND ($NameAr IS NULL OR bl_name_ar ILIKE '%' || $NameAr || '%')
  AND ($LegalTypeEn IS NULL OR bl_legal_type_en = $LegalTypeEn)
  AND ($LegalTypeAr IS NULL OR bl_legal_type_ar = $LegalTypeAr)
  AND ($EstDateFrom IS NULL OR bl_est_date >= $EstDateFrom)
  AND ($EstDateTo IS NULL OR bl_est_date <= $EstDateTo)
  AND ($ExpDateFrom IS NULL OR bl_exp_date >= $ExpDateFrom)
  AND ($ExpDateTo IS NULL OR bl_exp_date <= $ExpDateTo)
  AND ($TypeEn IS NULL OR bl_type_en = $TypeEn)
  AND ($TypeAr IS NULL OR bl_type_ar = $TypeAr)
  AND ($LicenseBranchFlag IS NULL OR license_branch_flag = $LicenseBranchFlag)
  AND ($FullAddress IS NULL OR bl_full_address ILIKE '%' || $FullAddress || '%')
  AND ($ParentLicenceLicenseNumber IS NULL OR parent_licence_license_number ILIKE '%' || $ParentLicenceLicenseNumber || '%')
  AND ($ParentLicenseIssuanceAuthorityEn IS NULL OR parent_license_issuance_authority_en = $ParentLicenseIssuanceAuthorityEn)
  AND ($ParentLicenseIssuanceAuthorityAr IS NULL OR parent_license_issuance_authority_ar = $ParentLicenseIssuanceAuthorityAr)
  AND ($RelationshipTypeEn IS NULL OR relationship_type_en = $RelationshipTypeEn)
  AND ($RelationshipTypeAr IS NULL OR relationship_type_ar = $RelationshipTypeAr)
  AND ($OwnerNationalityAr IS NULL OR owner_nationality_ar = $OwnerNationalityAr)
  AND ($OwnerGender IS NULL OR owner_gender = $OwnerGender)
  AND ($OwnerNationalityEn IS NULL OR owner_nationality_en = $OwnerNationalityEn)
  AND ($BusinessActivityCode IS NULL OR business_activity_code ILIKE '%' || $BusinessActivityCode || '%')
  AND ($BusinessActivityDescEn IS NULL OR business_activity_desc_en ILIKE '%' || $BusinessActivityDescEn || '%')
  AND ($BusinessActivityDescAr IS NULL OR business_activity_desc_ar ILIKE '%' || $BusinessActivityDescAr || '%')
  AND ($LicenseLatitude IS NULL OR license_latitude = $LicenseLatitude)
  AND ($LicenseLongitude IS NULL OR license_longitude = $LicenseLongitude)
  AND ($EstDateDFrom IS NULL OR bl_est_date_d >= $EstDateDFrom)
  AND ($EstDateDTo IS NULL OR bl_est_date_d <= $EstDateDTo)
  AND ($ExpDateDFrom IS NULL OR bl_exp_date_d >= $ExpDateDFrom)
  AND ($ExpDateDTo IS NULL OR bl_exp_date_d <= $ExpDateDTo)
  AND ($LatDd IS NULL OR lat_dd = $LatDd)
  AND ($LonDd IS NULL OR lon_dd = $LonDd)
ORDER BY parent_licence_license_number DESC
LIMIT $page_size OFFSET (($page - 1) * $page_size) 